name: Test

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run forge test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Run invariants tests
        run: |
          forge test --match-path 'test/invariants/*' -vvv

      - name: Run other tests with forking
        run: |
          forge test --no-match-path 'test/invariants/*' -vvv
        env:
          FOUNDRY_ETH_RPC_URL: https://cloudflare-eth.com
